--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.5
-- Dumped by pg_dump version 9.6.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;


create table if not exists student
(
    id bigint generated by default as identity
    constraint usr_pkey
    primary key,
    group_name text not null,
    number text unique,
    point bigint default 0

);

insert into student (group_name, number, point) values ('A', 101, 0);
insert into student (group_name, number, point) values ('A', 102, 0);
insert into student (group_name, number, point) values ('A', 103, 0);
insert into student (group_name, number, point) values ('A', 104, 0);
insert into student (group_name, number, point) values ('A', 105, 0);
insert into student (group_name, number, point) values ('A', 106, 0);
insert into student (group_name, number, point) values ('A', 107, 0);
insert into student (group_name, number, point) values ('A', 108, 0);
insert into student (group_name, number, point) values ('A', 109, 0);
insert into student (group_name, number, point) values ('A', 110, 0);
insert into student (group_name, number, point) values ('B', 111, 0);
insert into student (group_name, number, point) values ('B', 112, 0);
insert into student (group_name, number, point) values ('B', 113, 0);
insert into student (group_name, number, point) values ('B', 114, 0);
insert into student (group_name, number, point) values ('B', 115, 0);
--
-- PostgreSQL database dump complete
--